### ISSUE TITLE
error when message has text, or does not contain a url, or URL does not have a <title>

### ISSUE THREAD

**Issue by hamilton5** [Aciid/title-for-mumo#1]
ERROR title list index out of range
Traceback (most recent call last):
  File "/var/lib/mumble-server/mumo/worker.py", line 115, in run
    res = fu(_args, *_kwargs)
  File "modules/title.py", line 71, in userTextMessage
    print link[0]
IndexError: list index out of range

**Comment by Aciid** [comment]
This module is lacking tests and the error seems to be related that in new mumble api has changed majorly so that messages are parsed whether they contain anything that should be matched. I'm sorry, but since we are using Teamspeak nowadays this module is unmaintained and archived as a reference for anyone who still uses mumo for Mumble.

**Comment by hamilton5** [comment]
sad day, thank you.
